/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestCases;

import Models.CollisionHandler;
import Models.CreateShape;
import Models.Shape;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.ArrayList;
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;

/**
 * Test case: Circle, Square Collision 
 * Expected outcome: when a circle and a square touch a new circle of square will 
 * be generated at random, coming from the top center
 *
 * @author graces3
 */
public class CircleSquareCollision extends javax.swing.JFrame {

    static Color bgColor = new Color(255, 255, 255);
    static Graphics2D canvas;
    private final ArrayList<Shape> circles = new ArrayList<>();
    private final ArrayList<Shape> squares = new ArrayList<>();
    private CollisionHandler collisonHandler;
    private final Lock masterLock = new ReentrantLock();

    /**
     * Creates new form CircleSquareCollision
     */
    public CircleSquareCollision() {
        initComponents();
        canvas = (Graphics2D) mainCanvas1.getGraphics();
        canvas.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_OFF);
        int[] boundary = {0, 0, mainCanvas1.getWidth(), mainCanvas1.getHeight()};
        collisonHandler = new CollisionHandler(circles, squares, null, null, canvas, boundary, masterLock, bgColor);
        Thread chThread = new Thread(collisonHandler);
        chThread.start();
        CreateShape.createCircle(circles, canvas, mainCanvas1.getWidth(), mainCanvas1.getHeight(), bgColor, 1, masterLock);
        CreateShape.createSquare(squares, canvas, mainCanvas1.getWidth(), mainCanvas1.getHeight(), bgColor, 1, masterLock);
        circles.get(0).setTopLeftY(mainCanvas1.getHeight() / 2);
        circles.get(0).setSpeedY(0);
        squares.get(0).setTopLeftY(mainCanvas1.getHeight() / 2);
        squares.get(0).setSpeedY(0);
        circles.get(0).setTopLeftX(5);
        circles.get(0).setSpeedX(10);
        squares.get(0).setTopLeftX(mainCanvas1.getWidth() - 5);
        squares.get(0).setSpeedX(-10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainCanvas1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Test Case: Circle, Square Collision");
        setResizable(false);

        mainCanvas1.setBackground(new java.awt.Color(255, 255, 255));
        mainCanvas1.setToolTipText("");
        mainCanvas1.setMaximumSize(new java.awt.Dimension(845, 480));
        mainCanvas1.setName("Test Case: Circle, Circle Collission"); // NOI18N
        mainCanvas1.setPreferredSize(new java.awt.Dimension(845, 480));

        javax.swing.GroupLayout mainCanvas1Layout = new javax.swing.GroupLayout(mainCanvas1);
        mainCanvas1.setLayout(mainCanvas1Layout);
        mainCanvas1Layout.setHorizontalGroup(
            mainCanvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
        );
        mainCanvas1Layout.setVerticalGroup(
            mainCanvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainCanvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainCanvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CircleSquareCollision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CircleSquareCollision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CircleSquareCollision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CircleSquareCollision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CircleSquareCollision().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainCanvas1;
    // End of variables declaration//GEN-END:variables
}
