/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestCases;

import Models.CollisionHandler;
import Models.CreateShape;
import Models.Shape;
import Models.Windmill;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.ArrayList;
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;

/**
 * Test Case: Circle Hit Windmill
 * Expected outcome: the circle will change direction
 * 
 * @author Stefan
 */
public class CircleHitWindmill extends javax.swing.JFrame {

    static Color bgColor = new Color(255, 255, 255);
    static Graphics2D canvas;
    private final ArrayList<Shape> circles = new ArrayList<>();
    private CollisionHandler collisonHandler;
    private Windmill wm;
    private final Lock masterLock = new ReentrantLock();
    
    /**
     * Creates new form CircleHitWindmill
     */
    public CircleHitWindmill() {
        initComponents();
        canvas = (Graphics2D) mainCanvas1.getGraphics();
        canvas.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_OFF);
        // Boundary
        int[] boundary = {0, 0, mainCanvas1.getWidth(), mainCanvas1.getHeight()};
        // Windmill
        int[] arrayX = {118, 148, 148, 213, 213, 148, 148, 118, 118, 53, 53, 118}; // set the starting x cooridinates of the windmill
        int[] arrayY = {160, 160, 225, 225, 255, 255, 320, 320, 255, 255, 225, 225}; // set the starting y cooridinates of the windmill
        int[] rotatedArrayX = {87, 133, 179, 200, 155, 200, 179, 133, 87, 66, 112, 66}; // set the rotated x cooridinates of the windmill
        int[] rotatedArrayY = {174, 219, 174, 195, 240, 285, 307, 262, 307, 286, 240, 194}; // set the rotated y cooridinates of the windmill
        wm = new Windmill(arrayX, arrayY, rotatedArrayX, rotatedArrayY, 240, 214, new Color(0, 0, 0), bgColor, canvas);
        wm.setLock(masterLock);
        Thread wmThread = new Thread(wm);
        wmThread.start();
        // Collision handler
        collisonHandler = new CollisionHandler(circles, null, null, wm, canvas, boundary, masterLock, bgColor);
        Thread chThread = new Thread(collisonHandler);
        chThread.start();
        // Circle
        CreateShape.createCircle(circles, canvas, mainCanvas1.getWidth(), mainCanvas1.getHeight(), bgColor, 1, masterLock);
        circles.get(0).setTopLeftX(mainCanvas1.getWidth() - 5);
        circles.get(0).setTopLeftY(mainCanvas1.getHeight() /2);
        circles.get(0).setSpeedX(-10);
        circles.get(0).setSpeedY(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainCanvas1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Test Case: Circle Hit Windmill");
        setResizable(false);

        mainCanvas1.setBackground(new java.awt.Color(255, 255, 255));
        mainCanvas1.setToolTipText("");
        mainCanvas1.setMaximumSize(new java.awt.Dimension(845, 480));
        mainCanvas1.setName("Test Case: Circle, Circle Collission"); // NOI18N
        mainCanvas1.setPreferredSize(new java.awt.Dimension(845, 480));

        javax.swing.GroupLayout mainCanvas1Layout = new javax.swing.GroupLayout(mainCanvas1);
        mainCanvas1.setLayout(mainCanvas1Layout);
        mainCanvas1Layout.setHorizontalGroup(
            mainCanvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
        );
        mainCanvas1Layout.setVerticalGroup(
            mainCanvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainCanvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainCanvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CircleHitWindmill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CircleHitWindmill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CircleHitWindmill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CircleHitWindmill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CircleHitWindmill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainCanvas1;
    // End of variables declaration//GEN-END:variables
}
